In [1]:
import pandas as pd
import numpy as np
import pysurvival as pys
from pysurvival.models.semi_parametric import CoxPHModel
from sklearn.preprocessing import StandardScaler

In [2]:
dset = 'veteran'
folds = 10

In [3]:
fold = 0

In [4]:
trainset = pd.read_csv(f'Data/{dset}_folds/fold{fold}-train.csv', index_col=0)
testset = pd.read_csv(f'Data/{dset}_folds/fold{fold}-test.csv', index_col=0)

In [5]:
trainset = pd.get_dummies(trainset)
testset = pd.get_dummies(testset)

In [6]:
X_train = trainset.drop(['time', 'status'], axis=1).values
X_test = testset.drop(['time', 'status'], axis=1).values
T_train = trainset.time.values
T_test = testset.time.values
E_train = trainset.status.values
E_test = testset.status.values

In [7]:
model = CoxPHModel()

In [17]:
X_train = scaler.fit_transform(X_train)
model.fit(X_train, T_train, E_train, verbose=False)

CoxPHModel

In [26]:
T_pred = model.predict_survival(X_test)

In [28]:
T_pred.shape

(14, 87)

In [25]:
T_test

array([  7,  31,  45,  51, 216, 201, 122,  99,  36,  87,   3,  90,  82,
       156])

In [29]:
model.times

array([  1.,   2.,   4.,   7.,   8.,  10.,  11.,  12.,  13.,  15.,  16.,
        18.,  19.,  20.,  21.,  22.,  24.,  25.,  27.,  29.,  30.,  31.,
        33.,  35.,  42.,  43.,  44.,  48.,  49.,  51.,  52.,  53.,  54.,
        56.,  59.,  61.,  63.,  72.,  73.,  80.,  84.,  92.,  95.,  99.,
       100., 103., 105., 110., 111., 112., 117., 118., 126., 132., 133.,
       139., 140., 143., 144., 151., 153., 162., 164., 177., 186., 200.,
       228., 231., 242., 250., 260., 278., 283., 287., 314., 340., 357.,
       378., 384., 389., 392., 411., 467., 553., 587., 991., 999.])

In [30]:
T_train

array([144, 278, 103,  73,  30, 314,  92, 357,   4, 392,  24,  22,  56,
       182,  95,  51, 177, 287,  51,  84, 200, 162,  52, 162,   1, 384,
       411,  13, 283,  35,  29, 186, 164,  44,  54,  20, 118,  11, 110,
        61,   8,  18,  83,  25, 231,  72,  99, 111, 553,  97, 132,  16,
       991,  10,   2, 378,  24,  15, 153,  52, 587, 112, 250,   8, 100,
        30,  20,  27,  95,   8,  15,  33, 100,  19, 105,  59,  21, 111,
        63,  25,  54, 117, 260, 999, 151,   8,  80, 139,  31,  21,  12,
       133,  43,  48,   1,   7,  42, 143,  25,  52,  13,  80, 126,  25,
       140,  19, 467, 340, 242, 389,  53,   7, 231, 117,  12,  18, 123,
       103,  49,  18, 228,  87,  10])

In [31]:
import pysurvival.utils.metrics as metrics

In [32]:
metrics.concordance_index(model, X_test, T_test, E_test)

0.7032967032967034